export interface Run { id: number; name: string; ea_name: string; symbol: string | null; timeframe: string | null; date_from: string | null; date_to: string | null; broker: string | null; deposit: number | null; leverage: string | null; modelling_method: string | null; optimization_algorithm: string | null; criterion: string | null; result_count: number; parameter_names: string[]; created_at: string; source_filename: string; file_hash: string; warnings: string[] }
export interface Result { id: number; run_id: number; parameter_set_id: number; stable_set_id: string; full_hash: string; parameters: Record<string, string>; mt5_pass: string | null; result: number | null; profit: number | null; profit_pct: number | null; expected_payoff: number | null; profit_factor: number | null; recovery_factor: number | null; sharpe: number | null; equity_dd: number | null; trades: number | null; custom: number | null; candidate_id: number | null }
export interface DiscoveryMethod { optimization_algorithm: string | null; criterion: string | null; modelling_method: string | null }
export interface DiscoveryPolicy { max_equity_dd: number; min_profit_factor: number; min_trades: number; profit_above: number; min_recovery: number | null; min_sharpe: number | null; min_expected_payoff: number | null; min_result: number | null }
export interface DiscoveryPreview { run: Run; settings: DiscoveryMethod; recommended: DiscoveryMethod; settings_warnings: string[]; policy: DiscoveryPolicy; ranking: string[]; ranking_objective?: string; available_objectives?: string[]; top_count: number; total_results: number; qualifying_results: number; qualifying_sets: number; status: string; validation_status: string; items: (Result & { discovery_rank: number })[] }
export interface DiscoveryBatch { id: number; run_id: number; policy: DiscoveryPolicy; ranking: string[]; run_settings: DiscoveryMethod; selected_results: { result_id: number; parameter_set_id: number; full_hash: string; rank: number }[]; created_at: string }
export interface Candidate { id: number; notes: string; tags: string[]; baseline: Result; validation_status: string; overall_status: OverallStatus; pipeline: PipelineStage[]; run: CandidateRun; discovery_method: DiscoveryMethod; validation_method: string; discovery_evidence: { batch_id: number; rank: number; policy: DiscoveryPolicy; ranking: string[]; selected_at: string } | null }
export type Status = "NOT_TESTED" | "RUNNING" | "PASSED" | "WARNING" | "FAILED";
export type OverallStatus = "DISCOVERED" | "VALIDATING" | "FAILED" | "LIVE_CANDIDATE";
export interface PipelineStage { key: string; label: string; status: Status; required: boolean; tests: number; detail: string }
export interface CandidateRun { id: number; name: string; ea_name: string; symbol: string | null; timeframe: string | null; date_from: string | null; date_to: string | null; result_count: number; broker: string | null }
export interface MetricSet { profit: number | null; equity_dd: number | null; profit_factor: number | null; recovery_factor: number | null; sharpe: number | null; trades: number | null; win_rate: number | null }
export interface Warning { code: string; message: string; metric?: string }
export interface Delta { baseline: number | null; value: number | null; change: number | null; change_pct: number | null; degradation_pct?: number }
export interface RobustPoint { x: number; y: number | null; profit: number; equity_dd: number; profit_factor: number; trades: number; good: boolean; is_candidate: boolean }
export interface ValidationRecord { id: number; candidate_id: number; stage: string; stage_label: string; label: string; status: Status; metrics: Partial<MetricSet>; baseline: Partial<MetricSet>; baseline_source: string; comparison: { deltas: Record<string, Delta>; warnings: Warning[] }; settings: Record<string, string | number | null>; evidence: { regimes?: Record<string, Partial<MetricSet>>; in_sample?: { from: string | null; to: string | null }; out_of_sample?: { from: string; to: string }; classification?: string; message?: string; points?: RobustPoint[]; good_neighbours?: number; neighbours?: number }; status_overridden: boolean; notes: string; created_at: string }
export interface CandidateDetail extends Candidate { records: ValidationRecord[]; rules: ValidationRules; parameters: Record<string, string> }
export interface ValidationRules { profit_degradation_pct: number; drawdown_multiple: number; min_profit_factor: number; trade_change_pct: number; fail_warning_count: number; robustness_min_profit_factor: number; plateau_min_good_ratio: number; required_stages: string[]; warning_counts_as_pass: boolean }
export interface FunnelStep { key: string; label: string; count: number }
export interface StageCount { key: string; label: string; required: boolean; PASSED: number; RUNNING: number; WARNING: number; FAILED: number; NOT_TESTED: number }
export interface Page<T> { items: T[]; total: number }
export interface Condition { field: string; op: string; value: number }
export interface SetDetail { id: number; stable_set_id: string; full_hash: string; canonical_json: string; parameters: Record<string, string>; results: Result[]; result_count: number }
export interface ImportRecord { id: number; filename: string; file_hash: string; record_count: number; warnings: string[]; imported_at: string; run_id: number }
