import { test, expect } from "@playwright/test";
import path from "node:path";
import fs from "node:fs";
const root = path.resolve(__dirname, "../../..");
test("import → metadata → Explorer → filters → candidate → set detail", async ({ page }) => {
  const browserErrors: string[] = [];
  page.on("pageerror", e => browserErrors.push(e.message));
  await page.goto("/imports");
  const content = fs.readFileSync(path.join(root, "sample-data/mt5-optimization.xml"), "utf8").replace("<ss:Workbook", `<ss:Workbook acceptance="${Date.now()}"`);
  await page.getByLabel("MT5 XML file").setInputFiles({ name: "browser-acceptance.xml", mimeType: "application/xml", buffer: Buffer.from(content) });
  await page.getByLabel("Run name", { exact: true }).fill("Browser acceptance run");
  await page.getByRole("button", { name: "Import optimization", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Imported 12 results");
  await page.getByRole("link", { name: "Explore imported results" }).click();
  await expect(page.getByRole("heading", { name: "Optimization Explorer" })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "InpSwingLookback" })).toBeAttached();
  await expect(page.getByRole("link", { name: /SET-/ }).first()).toBeVisible();
  await page.getByRole("button", { name: "Filters", exact: true }).click();
  await page.getByLabel("Filter metric").selectOption("profit");
  await page.getByLabel("Filter operator").selectOption("gt");
  await page.getByLabel("Filter value").fill("1000");
  await page.getByRole("button", { name: "Add", exact: true }).click();
  await expect(page.locator(".filter-chip")).toContainText("Profit > 1000");
  await expect(page.locator(".loading")).toHaveCount(0);
  await page.getByRole("button", { name: "Profit", exact: true }).click();
  await expect(page.locator(".loading")).toHaveCount(0);
  await page.getByLabel("Select page", { exact: true }).check();
  await page.getByRole("button", { name: "Export selected", exact: true }).click();
  await page.getByRole("button", { name: "Promote to candidate", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("candidates created");
  await page.getByRole("link", { name: "View candidates", exact: false }).click();
  await expect(page.getByRole("heading", { name: "Candidate Sets", exact: true })).toBeVisible();
  await expect(page.locator(".candidate-grid .panel").first()).toBeVisible();
  await page.locator(".candidate-grid .panel").first().getByRole("textbox", { name: /Notes for/ }).fill("Browser verified shortlist");
  await page.locator(".candidate-grid .panel").first().getByRole("button", { name: "Save notes" }).click();
  await expect(page.getByRole("status")).toContainText("Notes and tags saved");
  await page.locator(".candidate-grid .panel").first().getByRole("link", { name: "Set detail" }).click();
  await expect(page.getByRole("heading", { name: "Complete EA inputs" })).toBeVisible();
  await expect(page.locator("main")).toContainText("InpTFZone");
  expect(browserErrors).toEqual([]);
});

test("thousands of rows remain paginated; sort, search, visibility and metadata work", async ({ page }) => {
  await page.goto("/explorer?run=1");
  await expect(page.locator(".pagination")).toContainText("5,000 records");
  await expect(page.locator("tbody tr")).toHaveCount(50);
  const firstID = await page.locator("tbody tr").first().innerText();
  await page.getByLabel("Next page", { exact: true }).click();
  await expect(page.locator(".pagination")).toContainText("51–100");
  await expect(page.locator("tbody tr")).toHaveCount(50);
  expect(await page.locator("tbody tr").first().innerText()).not.toEqual(firstID);
  await page.getByRole("button", { name: "Filters", exact: true }).click();
  await page.getByRole("button", { name: "Research preset" }).click();
  await expect(page.locator(".filter-chip")).toHaveCount(4);
  await expect(page.locator(".loading")).toHaveCount(0);
  await page.getByRole("button", { name: "Columns", exact: true }).click();
  await page.locator(".columns-popover").getByLabel("Sharpe", { exact: true }).uncheck();
  await expect(page.getByRole("columnheader", { name: "Sharpe", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Clear", exact: true }).click();
  const setID = (await page.locator("tbody .table-link").first().innerText()).trim();
  await page.getByLabel("Search sets or parameters").fill(setID);
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await page.screenshot({ path: path.join(root, "docs/screenshots/explorer.png"), fullPage: true });
  await page.goto("/runs/1");
  await expect(page.getByRole("heading", { name: "Run metadata" })).toBeVisible();
  await expect(page.locator("main")).toContainText("XAUUSD");
  await expect(page.locator("main")).toContainText("3,000.00");
  await page.getByRole("button", { name: "Rename", exact: true }).click();
  await page.getByLabel("Run name", { exact: true }).fill("Synthetic · HybridSMC XAUUSD M1 · 5,000 passes");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("5,000 passes");
});

test("dashboard and responsive workspace render", async ({ page }) => {
  await page.goto("/dashboard");
  await expect(page.locator(".stat-value").first()).not.toHaveText("—");
  await page.screenshot({ path: path.join(root, "docs/screenshots/dashboard.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("heading", { name: "Dashboard", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
});
