"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, Save, Download, Workflow } from "lucide-react";
import { api, jsonBody, number } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { Heading, ErrorBox, Empty, Pagination } from "@/components/common";
import { Button } from "@/components/ui/button";
import { downloadSetFile } from "@/lib/mt5";
import { DiscoveryEvidence } from "@/features/discovery/discovery-evidence";
import { OverallBadge, PipelineView } from "@/features/candidates/pipeline";
import type { Candidate, Page } from "@/types";
function CandidateCard({ candidate }: { candidate: Candidate }) {
  const [notes, setNotes] = useState(candidate.notes), [tags, setTags] = useState(candidate.tags.join(", ")), [message, setMessage] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const r = candidate.baseline;
  async function save() { setBusy(true); setError(""); setMessage(""); try { await api(`/candidates/${candidate.id}`, { ...jsonBody({ notes, tags: tags.split(",").map(t => t.trim()).filter(Boolean) }), method: "PATCH" }); setMessage("Notes and tags saved."); } catch(e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <div className="panel"><div className="panel-head"><Link className="table-link mono" href={`/sets/${r.parameter_set_id}`}>{r.stable_set_id}</Link><div style={{ display: "flex", gap: 8, alignItems: "center" }}><Button size="sm" variant="outline" onClick={() => downloadSetFile(r.parameters, `${r.stable_set_id}`)}><Download size={13} /> .set</Button><Button size="sm" asChild><Link href={`/workflow?candidate=${candidate.id}&step=3`}><Workflow size={13} /> Workflow</Link></Button></div></div><div className="panel-body"><DiscoveryEvidence candidate={candidate} /><small>BASELINE · RUN #{r.run_id} · MT5 PASS {r.mt5_pass}</small><div className="metric-grid">{[["Profit", r.profit], ["Profit %", r.profit_pct], ["Equity DD %", r.equity_dd], ["Profit Factor", r.profit_factor], ["Recovery", r.recovery_factor], ["Expected payoff", r.expected_payoff], ["Sharpe", r.sharpe], ["Trades", r.trades]].map(([label,value]) => <div key={label as string}><small>{label}</small><b className={label === "Profit" ? "green mono" : "mono"}>{number(value as number | null, label === "Trades" ? 0 : 2)}</b></div>)}</div><div className="parameter-chips">{Object.entries(r.parameters).slice(0,6).map(([k,v]) => <span key={k} className="parameter-chip">{k.replace(/^Inp/,"")} <b>{v}</b></span>)}</div><div className="section-gap"><PipelineView stages={candidate.pipeline} setId={r.stable_set_id} /><div className="overall-line">Overall Status: <OverallBadge status={candidate.overall_status} /></div></div><label className="field section-gap">Research notes<textarea aria-label={`Notes for ${r.stable_set_id}`} className="candidate-notes" value={notes} maxLength={10000} placeholder="Record why this configuration was selected…" onChange={e => setNotes(e.target.value)} /></label><label className="field">Tags, separated by commas<input value={tags} onChange={e => setTags(e.target.value)} placeholder="shortlist, low-drawdown" /></label><ErrorBox message={error} />{message && <p className="success" role="status">{message}</p>}<div className="form-actions"><Button size="sm" variant="outline" disabled={busy} onClick={save}><Save size={14} />Save notes</Button><Link href={`/sets/${r.parameter_set_id}`} className="table-link" style={{ marginLeft: "auto", fontSize: 12 }}>Set detail →</Link><Link href={`/candidates/${candidate.id}`} className="table-link" style={{ fontSize: 12 }}>Validation pipeline →</Link></div></div></div>;
}
export function Candidates() {
  const [page, setPage] = useState(1);
  const { data, error, loading } = useApi<Page<Candidate>>(`/candidates?page=${page}&page_size=12`);
  return <><Heading eyebrow="RESEARCH SHORTLIST" title="Candidate Sets" description="Track the configurations selected for further validation."><Button variant="outline" asChild><Link href="/discovery">Discover candidates<ArrowRight size={15} /></Link></Button></Heading><ErrorBox message={error} /><div className="notice">Candidates preserve the selected optimization result as their baseline. Selection does not imply a passed validation test or future profitability.</div>{loading ? <div className="loading">Loading candidates…</div> : !data?.items.length ? <div className="panel"><Empty title="Your shortlist is empty" message="Select results in Optimization Explorer and promote them to candidates." href="/explorer" /></div> : <><div className="candidate-grid">{data.items.map(c => <CandidateCard key={c.id} candidate={c} />)}</div><Pagination page={page} pageSize={12} total={data.total} onPage={setPage} /></>}</>;
}
