"""foundation"""
from alembic import op
import sqlalchemy as sa

revision = '5563350a2570'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_advisors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('import_type', sa.String(length=30), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('parameter_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_hash', sa.String(length=64), nullable=False),
    sa.Column('stable_set_id', sa.String(length=12), nullable=False),
    sa.Column('canonical_json', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_hash')
    )
    op.create_index(op.f('ix_parameter_sets_stable_set_id'), 'parameter_sets', ['stable_set_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=40), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['parameter_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_parameter_set_id'), 'backtest_runs', ['parameter_set_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['parameter_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ea_id', sa.Integer(), nullable=False),
    sa.Column('import_file_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=80), nullable=True),
    sa.Column('timeframe', sa.String(length=30), nullable=True),
    sa.Column('date_from', sa.String(length=40), nullable=True),
    sa.Column('date_to', sa.String(length=40), nullable=True),
    sa.Column('broker', sa.String(length=200), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('leverage', sa.String(length=40), nullable=True),
    sa.Column('modelling_method', sa.String(length=120), nullable=True),
    sa.Column('optimization_algorithm', sa.String(length=120), nullable=True),
    sa.Column('criterion', sa.String(length=120), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('parameter_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ea_id'], ['expert_advisors.id'], ),
    sa.ForeignKeyConstraint(['import_file_id'], ['import_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_file_id')
    )
    op.create_table('parameter_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['parameter_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_set_id', 'name')
    )
    op.create_index(op.f('ix_parameter_values_parameter_set_id'), 'parameter_values', ['parameter_set_id'], unique=False)
    op.create_table('equity_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_points_backtest_run_id'), 'equity_points', ['backtest_run_id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=False),
    sa.Column('mt5_pass', sa.String(length=80), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('expected_payoff', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('recovery_factor', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('custom', sa.Float(), nullable=True),
    sa.Column('equity_dd', sa.Float(), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['parameter_sets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['optimization_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_parameter_set_id'), 'optimization_results', ['parameter_set_id'], unique=False)
    op.create_index(op.f('ix_optimization_results_run_id'), 'optimization_results', ['run_id'], unique=False)
    op.create_index('ix_result_run_dd', 'optimization_results', ['run_id', 'equity_dd'], unique=False)
    op.create_index('ix_result_run_pf', 'optimization_results', ['run_id', 'profit_factor'], unique=False)
    op.create_index('ix_result_run_profit', 'optimization_results', ['run_id', 'profit'], unique=False)
    op.create_index('ix_result_run_trades', 'optimization_results', ['run_id', 'trades'], unique=False)
    op.create_table('validation_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_set_id', sa.Integer(), nullable=False),
    sa.Column('baseline_result_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_result_id'], ['optimization_results.id'], ),
    sa.ForeignKeyConstraint(['parameter_set_id'], ['parameter_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_set_id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_sets')
    op.drop_table('validation_tests')
    op.drop_index('ix_result_run_trades', table_name='optimization_results')
    op.drop_index('ix_result_run_profit', table_name='optimization_results')
    op.drop_index('ix_result_run_pf', table_name='optimization_results')
    op.drop_index('ix_result_run_dd', table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_run_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_parameter_set_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_equity_points_backtest_run_id'), table_name='equity_points')
    op.drop_table('equity_points')
    op.drop_index(op.f('ix_parameter_values_parameter_set_id'), table_name='parameter_values')
    op.drop_table('parameter_values')
    op.drop_table('optimization_runs')
    op.drop_table('notes')
    op.drop_index(op.f('ix_backtest_runs_parameter_set_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_table('users')
    op.drop_index(op.f('ix_parameter_sets_stable_set_id'), table_name='parameter_sets')
    op.drop_table('parameter_sets')
    op.drop_table('import_files')
    op.drop_table('expert_advisors')
    op.drop_table('experiments')
    # ### end Alembic commands ###
