"use client";
import Link from "next/link";
import { useApi } from "@/hooks/use-api";
import { Heading, ErrorBox } from "@/components/common";
import { number } from "@/lib/api";
import type { SetDetail as Detail } from "@/types";
export function SetDetail({ id }: { id: string }) {
  const { data, error, loading } = useApi<Detail>(`/sets/${id}`);
  if (!data) return <><ErrorBox message={error} />{loading && <div className="loading">Loading parameter set…</div>}</>;
  return <><Heading eyebrow="STABLE PARAMETER CONFIGURATION" title={data.stable_set_id} description="One input configuration. A reproducible identity across optimization runs." /><div className="panel"><div className="panel-head"><h2>Complete EA inputs</h2><span className="badge neutral">{Object.keys(data.parameters).length} INPUTS</span></div><div className="table-wrap"><table><thead><tr><th>Parameter</th><th>Canonical value</th></tr></thead><tbody>{Object.entries(data.parameters).map(([k,v]) => <tr key={k}><td className="mono">{k}</td><td className="mono blue">{v}</td></tr>)}</tbody></table></div></div><div className="panel"><div className="panel-head"><h2>Optimization history</h2><span className="badge neutral">{data.result_count} RESULTS</span></div><div className="table-wrap"><table><thead><tr><th>Run</th><th>MT5 Pass</th><th>Profit</th><th>Profit %</th><th>DD %</th><th>PF</th><th>Recovery</th><th>Sharpe</th><th>Trades</th></tr></thead><tbody>{data.results.map(r => <tr key={r.id}><td><Link className="table-link" href={`/runs/${r.run_id}`}>Run #{r.run_id}</Link></td><td>{r.mt5_pass}</td><td className="green mono">{number(r.profit)}</td><td>{number(r.profit_pct)}</td><td>{number(r.equity_dd)}</td><td>{number(r.profit_factor)}</td><td>{number(r.recovery_factor)}</td><td>{number(r.sharpe)}</td><td>{r.trades}</td></tr>)}</tbody></table></div>{data.result_count > 50 && <div className="notice">Showing the latest 50 results. Search {data.stable_set_id} in Explorer to browse all results.</div>}</div><div className="panel"><div className="panel-head"><h2>Identity and provenance</h2></div><div className="panel-body"><small>FULL SHA-256</small><p className="hash mono">{data.full_hash}</p><small className="section-gap">CANONICAL INPUT JSON</small><p className="hash mono">{data.canonical_json}</p></div></div><div className="notice">Further validation is not tested in Phase 1. Backtest and execution evidence will attach to this parameter set in Phase 2.</div></>;
}
